do_filtering: True
do_reconstruction: True
use_velocities: False
save_npy: True

# MD Run Parameters
dt: 0.005
nx: 60
ny: 60
nz: 1

# SED Parameters
direction: [1,0,0]
n_kpoints: 25 #should equal # uc in chosen direction
bz_coverage: 2 #gives gamma to k to m to k to gamma
max_freq: 50
# Filtering Parameters
wmin: 35 
wmax: 37
amplitude: 10

