do_filtering: False
do_reconstruction: False
use_velocities: True
save_npy: True

# MD Run Parameters
dt: 0.005
nx: 60
ny: 60
nz: 1

# SED Parameters
direction: x
n_kpoints: 60 #should equal # uc in chosen direction
bz_coverage: 0.5 #gives gamma to k to m to k to gamma
max_freq: 50
# Filtering Parameters
wmin: 35 
wmax: 37
kmin: 1.55
kmax: 1.75

# Reconstruction Parameters
amplitude: 1


